services:
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset_container
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: ${SUPERSET_LOAD_EXAMPLES}
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PYTHONPATH: /app/pythonpath
    depends_on:
      - db
    volumes:
      - superset_data:/app/superset_home
    networks:
      - superset-net

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - superset-net
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: {}
  superset_data: {}

networks:
  superset-net:
    driver: bridge