services:
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset_container
    ports:
      - "${SUPERSET_PORT}:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "${SUPERSET_LOAD_EXAMPLES}"
      SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"
      # Variables de entorno para MySQL
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      - db
    volumes:
      - superset_data:/app/superset_home
      - ./superset/init_superset.sh:/app/docker/init_superset.sh
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  superset_data: